name: interior_ai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.1.1
  flutter_bloc: ^9.1.1
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  dio: ^5.9.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.0.10+1
  get_it: ^9.2.0
  share_plus: ^10.1.4
  in_app_review: ^2.0.10
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  gal: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/home/
    - assets/png/onboarding/
    - assets/png/onboarding_mini/
    - assets/png/onboarding_result/
    - assets/png/interrior_design/
    - assets/png/garden_design/
    - assets/png/exterior_design/
    - assets/floor_restyle/
    - assets/png/paywall/
    - assets/png/settings/
    - assets/svg/home/
    - assets/svg/interior_design/
    - assets/svg/settings/
    - assets/svg/replace_objects/
    - assets/svg/floor_restyle/
