import 'package:flutter/material.dart';

final class AppColors {
  static const Color ghostWhite = Color(0xffFAF9FC);
  static const Color smokyBlack = Color(0xff0D0D0D);
  static const Color nickel = Color(0xff737373);
  static const Color platinum = Color(0xffE6E6E6);
  static const Color pureWhite = Color(0xffFFFEFE);
  static const Color buttonBlue = Color(0xff2EA2EF);
  static const Color white = Colors.white;
  static const Color lavenderBlush = Color(0xffFCEDEF);
  static const Color palePink = Color(0xffFFDBDC);
  static const Color jasper = Color(0xffD74247);
  static const Color hanPurple = Color(0xff6720FF);
  static const Color hanPurple2 = Color(0xff5F25F5);
  static const Color magnolia = Color(0xffF5F5FF);
  static const Color lavender = Color(0xffE7E6FC);
  static const Color mediumPurple = Color(0xff9178E3);
  static const Color blueberry = Color(0xff4777FF);
  static const Color burntSienna = Color(0xffE56F4A);
  static const Color lemonCurry = Color(0xffCF9128);
  static const Color black = Color(0xff010101);
  static const Color coralRed = Color(0xffFF453A);
  static const Color azure = Color(0xff007AFF);
  static const Color spanishGray = Color(0xff9E9E9E);
  static const Color softPurple = Color(0xff9881FF);
  static const Color softPurpleFaint = Color(0x339881FF);
  static const Color cloudGray = Color(0xffF3F2F6);
  static const Color disabledGray = Color(0xffE3E1E8);
  static const Color disabledText = Color(0xffAFADB8);
  static const Color gradientBlue = Color(0xff539CF6);
  static const Color gradientPurple = Color(0xffA66CEC);
  static const Color paletteScrim = Color(0x995E5E5E);
  static const Color progressArcStart = Color(0xff71C6F6);
  static const Color progressArcEnd = Color(0xffA05DF5);
  static const Color styleScrim = Color(0x99323232);
  static const Color richBlack = Color(0xff170B1F);
  static const Color gainsboro = Color(0xffD9D9D9);
  static const Color sonicSilver = Color(0xff757575);
  static const Color whiteSmoke = Color(0xffF5F5F5);
  static const Color homeNavBarText = Color(0xff9881FF);
}
